    # FROM permet de définir l’image source
    # LABEL permet d’ajouter des métadonnées à une image
    # RUN permet d’exécuter des commandes dans votre conteneur
    # ADD permet d’ajouter des fichiers dans votre conteneur
    # WORKDIR permet de définir votre répertoire de travail
    # EXPOSE permet de définir les ports d’écoute par défaut
    # VOLUME permet de définir les volumes utilisables
    # CMD permet de définir la commande par défaut lors de l’exécution de vos conteneurs Docker.

    FROM node
    EXPOSE 3000
    